robot_ip: 192.168.1.246
test_time: '2026-05-19 13:32:12'
moves:
- name: Hello
  api_id: 1016
  category: gesture
  status: SKIPPED
  duration_seconds: null
  height_range: null
  modes_observed: null
- name: Stretch
  api_id: 1017
  category: gesture
  status: SKIPPED
  duration_seconds: null
  height_range: null
  modes_observed: null
- name: Dance1
  api_id: 1022
  category: dance
  status: SKIPPED
  duration_seconds: null
  height_range: null
  modes_observed: null
- name: Dance2
  api_id: 1023
  category: dance
  status: SKIPPED
  duration_seconds: null
  height_range: null
  modes_observed: null
- name: Pose
  api_id: 1028
  category: gesture
  status: TIMEOUT
  duration_seconds: 10.04
  height_range: 0.308-0.309
  modes_observed: '{0}'
- name: Scrape
  api_id: 1029
  category: playful
  status: OK
  duration_seconds: 7.45
  height_range: 0.156-0.355
  modes_observed: '{0}'
- name: FrontJump
  api_id: 1031
  category: trick
  status: OK
  duration_seconds: 4.09
  height_range: 0.118-0.334
  modes_observed: '{0}'
- name: FrontPounce
  api_id: 1032
  category: trick
  status: OK
  duration_seconds: 3.66
  height_range: 0.185-0.383
  modes_observed: '{0}'
- name: FingerHeart
  api_id: 1036
  category: gesture
  status: OK
  duration_seconds: 6.67
  height_range: 0.156-0.351
  modes_observed: '{0}'
- name: Wallow
  api_id: 1021
  category: playful
  status: REJECTED(3203)
  duration_seconds: null
  height_range: null
  modes_observed: null
- name: WiggleHips
  api_id: 1033
  category: gesture
  status: REJECTED(3203)
  duration_seconds: null
  height_range: null
  modes_observed: null
- name: StandOut
  api_id: 1039
  category: gesture
  status: REJECTED(3203)
  duration_seconds: null
  height_range: null
  modes_observed: null
- name: CrossWalk
  api_id: 1051
  category: step
  status: REJECTED(3203)
  duration_seconds: null
  height_range: null
  modes_observed: null
- name: Handstand
  api_id: 1301
  category: trick
  status: REJECTED(3203)
  duration_seconds: null
  height_range: null
  modes_observed: null
- name: CrossStep
  api_id: 1302
  category: step
  status: REJECTED(3203)
  duration_seconds: null
  height_range: null
  modes_observed: null
- name: OnesidedStep
  api_id: 1303
  category: step
  status: REJECTED(3203)
  duration_seconds: null
  height_range: null
  modes_observed: null
- name: Bound
  api_id: 1304
  category: trick
  status: REJECTED(3203)
  duration_seconds: null
  height_range: null
  modes_observed: null
- name: MoonWalk
  api_id: 1305
  category: dance
  status: REJECTED(3203)
  duration_seconds: null
  height_range: null
  modes_observed: null
- name: CrossStep_MCF
  api_id: 2051
  category: step-mcf
  status: REJECTED(3202)
  duration_seconds: null
  height_range: null
  modes_observed: null
- name: HandStand_MCF
  api_id: 2044
  category: trick-mcf
  status: REJECTED(3202)
  duration_seconds: null
  height_range: null
  modes_observed: null
- name: FreeBound_MCF
  api_id: 2046
  category: trick-mcf
  status: REJECTED(3202)
  duration_seconds: null
  height_range: null
  modes_observed: null
- name: FreeJump_MCF
  api_id: 2047
  category: trick-mcf
  status: REJECTED(3202)
  duration_seconds: null
  height_range: null
  modes_observed: null
- name: FreeWalk_MCF
  api_id: 2045
  category: step-mcf
  status: TIMEOUT
  duration_seconds: 15.04
  height_range: 0.312-0.312
  modes_observed: '{0}'
- name: ClassicWalk_MCF
  api_id: 2049
  category: step-mcf
  status: REJECTED(3202)
  duration_seconds: null
  height_range: null
  modes_observed: null
- name: WalkUpright_MCF
  api_id: 2050
  category: step-mcf
  status: REJECTED(3202)
  duration_seconds: null
  height_range: null
  modes_observed: null
